version: '3.3'
services: 
  user-service:
    image: worker-01:5000/user-service
    build: ./user
    networks: 
      - default
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  meter-service:
    image: worker-01:5000/meter-service
    build: ./meter
    networks: 
      - default
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  collection-service:
    image: worker-01:5000/collection-service
    build: ./collection
    networks: 
      - default
    volumes:
      - '/pool-data/key:/key'
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  access-control-service:
    image: worker-01:5000/access-control-service
    build: ./access-control
    networks: 
      - default
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  ticket-service:
    image: worker-01:5000/ticket-service
    build: ./ticket
    networks: 
      - default
    volumes:
      - '/pool-data/key:/key'
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  kong:
    # image: worker-01:5000/kong
    image: kong
    # build: ./kong
    privileged: true
    tty: true
    networks: 
      - default
    depends_on:
      - kong-database
    ports:
      - '8080:8000'
      - '443:443'
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    # volumes: 
    #   - '/pool-data/letsencrypt/etc/letsencrypt:/etc/letsencrypt'

  kong-dashboard:
    image: 'pgbi/kong-dashboard:v2'
    depends_on:
      - kong
    networks: 
      - default 
    ports:
      - '8081:8080'

  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
    networks: 
      - default
    ports:
      - "7474:7474"
      - "7687:7687"

  mongo:
    image: mongo

  kong-database:
    image: 'postgres:9.4'
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    networks: 
      - default
    volumes:
      - '/pool-data/kong-data:/var/lib/postgresql/data'
      
  swagger:
    image: worker-01:5000/swagger
    build: ./swagger
    networks: 
      - default
    environment:
      - SWAGGER_JSON=/doc/data-exchange/data-exchage-swagger.json

networks:
  default:
    attachable: true
    driver: store/weaveworks/net-plugin:latest_release
