version: '3.4'
services: 
  user-service:
    image: worker1:5000/user-service
    build: ./user
    networks: 
      - default
    extra_hosts:
      - "mongodb-service:192.168.2.199"
    env_file: 
      - ./app.env
    ports:
      - '9000:80'
    dns: 8.8.8.8
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M
        reservations:
          cpus: '0.25'
          memory: 1000M
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: any

  meter-service:
    image: worker1:5000/meter-service
    build: ./meter
    networks: 
      - default
    extra_hosts:
      - "mongodb-service:192.168.2.199"
    env_file: 
      - ./app.env
    ports:
      - '9001:80'
    dns: 8.8.8.8
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M
        reservations:
          cpus: '0.25'
          memory: 1000M
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: any

  collection-service:
    image: worker1:5000/collection-service
    build: ./collection
    networks: 
      - default
    extra_hosts:
      - "mongodb-service:192.168.2.199"
    env_file: 
      - ./app.env
    dns: 8.8.8.8
    ports:
      - '9002:80'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M
        reservations:
          cpus: '0.25'
          memory: 1000M
      replicas: 3
      update_config:
        parallelism: 1
      restart_policy:
        condition: any

  access-control-service:
    image: worker1:5000/access-control-service
    build:
      context: ./access-control
      network: host
    networks: 
      - default
    extra_hosts:
      - "mongodb-service:192.168.2.199"
      - "neo4j-server:192.168.2.200"
    env_file: 
      - ./app.env
    dns: 8.8.8.8
    ports:
      - '9003:80'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M
        reservations:
          cpus: '0.25'
          memory: 1000M
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: any
                
  ticket-service:
    image: worker1:5000/ticket-service
    build: ./ticket
    networks: 
      - default
    extra_hosts:
      - "mongodb-service:192.168.2.199"
    env_file: 
      - ./app.env
    dns: 8.8.8.8
    ports:
      - '9004:80'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M
        reservations:
          cpus: '0.25'
          memory: 1000M
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: any
  swagger:
    image: worker1:5000/swagger
    build: ./swagger
    networks: 
      - default
    ports:
      - '9005:80'
    environment:
      - SWAGGER_JSON=/data-exchange/swagger.json
      # - BASE_URL=/api/v1/docs/data-exchange
    deploy:
      restart_policy:
        condition: any

networks:
  default:
    attachable: true
