version: '3.3'
services: 
  user-service:
    image: worker-01:5000/user-service
    build: ./user
    networks: 
      - default
    extra_hosts:
      - "mongo:172.16.0.6"
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  meter-service:
    image: worker-01:5000/meter-service
    build: ./meter
    networks: 
      - default
    extra_hosts:
      - "mongo:172.16.0.6"
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  collection-service:
    image: worker-01:5000/collection-service
    build: ./collection
    networks: 
      - default
    extra_hosts:
      - "mongo:172.16.0.6"
    # volumes:
      # - '/home/centos/ha-storage/key:/key'
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  access-control-service:
    image: worker-01:5000/access-control-service
    build: ./access-control
    networks: 
      - default
    extra_hosts:
      - "mongo:172.16.0.6"
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  ticket-service:
    image: worker-01:5000/ticket-service
    build: ./ticket
    networks: 
      - default
    extra_hosts:
      - "mongo:172.16.0.6"
    # volumes:
      # - '/home/centos/ha-storage/key:/key'
    deploy:
      replicas: 2
      restart_policy:
        condition: any
  kong:
    image: worker-01:5000/kong
    # image: kong
    build: ./kong
    networks: 
      - default
    depends_on:
      - kong-database
    ports:
      # - '80:8000'
      - '80:80'
      - '443:443'
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    deploy:
      restart_policy:
        condition: any
    volumes: 
      - '/home/centos/ha-storage/cert:/cert'

  kong-dashboard:
    image: 'pgbi/kong-dashboard:v2'
    depends_on:
      - kong
    networks: 
      - default 
    ports:
      - '8081:8080'
    deploy:
      restart_policy:
        condition: any

  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
    networks: 
      - default
    volumes:
      - '/home/centos/ha-storage/neo4j:/data'
    ports:
      - "7474:7474"
      - "7687:7687"
    deploy:
      restart_policy:
        condition: any

  # mongo:
  #   image: mongo
  #   deploy:
  #     restart_policy:
  #       condition: any

  kong-database:
    image: 'postgres:9.4'
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    networks: 
      - default
    volumes:
      - '/home/centos/ha-storage/kong-data:/var/lib/postgresql/data'
    deploy:
      restart_policy:
        condition: any
      
  swagger:
    image: worker-01:5000/swagger
    build: ./swagger
    networks: 
      - default
    environment:
      - SWAGGER_JSON=/doc/data-exchange/data-exchage-swagger.json
    deploy:
      replicas: 2
      restart_policy:
        condition: any

networks:
  default:
    attachable: true
    driver: store/weaveworks/net-plugin:latest_release
