version: "3"
networks:
  kong-net:
    driver: bridge
services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    restart: always
    volumes:
      - /home/centos/postgres-data:/var/lib/postgresql/data
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5
  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:1.0.1
    command: "kong migrations bootstrap && kong migrations up"
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
    links:
      - kong-database
    depends_on:
      - kong-database
  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    # image: kong:1.0.1
    build: .
    restart: always
    networks:
      - kong-net
    extra_hosts:
      - "worker1:192.168.2.2"
      - "worker2:192.168.2.2"
    environment:
      KONG_PG_HOST: kong-database
      # KONG_PROXY_LISTEN: 0.0.0.0:8000
      # KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
    - "8001:8001"
    - "80:8000"
    - "443:8443"
  #######################################
  # Konga database
  #######################################
  konga-db:
    image: mongo
    networks:
      - kong-net
    volumes:
      - /home/centos/mongo-data:/data/db
    restart: always
  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    restart: always
    networks:
      - kong-net
    environment:
      DB_ADAPTER: mongo
      DB_HOST: konga-db
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      NODE_ENV: production
    depends_on:
      - konga-db
    ports:
      - "1337:1337"